spring.application.name=englishlearning

spring.datasource.url=jdbc:postgresql://localhost:5432/english_learning_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# API Key của Google Gemini
gemini.api.key=${GOOGLE_API_KEY}
