"""Original teaching/demo materials; fictional people, organisations and chart data."""
EXAMS = []
def mc(text, options, answer, tag, explanation, level=None):
    return dict(text=text, options=options, answer=answer, tag=tag, explanation=explanation, level=level, type='MULTIPLE_CHOICE_SINGLE')
def tf(text, answer, explanation, level='ADVANCED'):
    return dict(text=text, answer=answer, tag='TRUE_FALSE_NOT_GIVEN', explanation=explanation, level=level, type='TRUE_FALSE_NOT_GIVEN')
def add(course, lesson, slug, title, skill, level, objective, content, questions, script=None, role='PRACTICE', teaching='', rate=None):
    EXAMS.append(dict(course=course, lesson=lesson, slug=slug, title=title, skill=skill, level=level, objective=objective, content=content, questions=questions, script=script, role=role, teaching=teaching, rate=rate))

add(5,57,'01_doc_ho_so_ca_nhan','Đọc hồ sơ cá nhân','READING','BEGINNER','Tìm thông tin cá nhân được nêu rõ trong đoạn ngắn.',
"""My name is Anna. I am 24 years old and I come from Da Nang. I now live in Hanoi because I work at a children's hospital there. I am a nurse. I share a small apartment with my sister, Mai. She is a university student. From Monday to Friday, my shift starts at seven in the morning. I usually take the bus to work. After work, I cook dinner and read books. On Saturdays, I visit a nearby park with Mai. We enjoy walking there. I am learning English because I want to talk to visitors from other countries at the hospital.""",[
mc('Where does Anna live now?',['Da Nang','Hanoi','Hue','Ho Chi Minh City'],'B','DETAIL','“I now live in Hanoi” là nơi đang sống; Da Nang là nơi xuất thân.'),
mc('What does Anna do?',['She is a university student.','She is a teacher.','She is a nurse.','She is a bus driver.'],'C','DETAIL','“I am a nurse.” Người học đại học là Mai.'),
mc('Who shares the apartment with Anna?',['Her sister.','Her mother.','Her friend.','Her colleague.'],'A','DETAIL','“I share a small apartment with my sister, Mai.”'),
mc("When does Anna's shift start on weekdays?",['At six in the morning.','At eight in the morning.','At seven in the evening.','At seven in the morning.'],'D','DETAIL','“My shift starts at seven in the morning.”'),
mc('What do Anna and Mai do on Saturdays?',['Work at the hospital.','Walk in a park.','Attend an English class.','Visit their parents.'],'B','DETAIL','“We enjoy walking there” nói về công viên họ đến vào thứ Bảy.')],teaching='Đọc câu hỏi rồi tìm câu có thông tin tương ứng. Phân biệt nơi xuất thân với nơi đang sống. nurse = y tá; shift = ca làm việc. Ví dụ: “Anna is 24” trả lời “How old is Anna?”.')

add(5,58,'02_nghe_lich_sinh_hoat','Nghe lịch sinh hoạt','LISTENING','BEGINNER','Nghe giờ và hoạt động trong lịch sinh hoạt quen thuộc.','A weekday routine',[
mc('What time does Ben get up?',['At six thirty.','At six.','At seven.','At seven thirty.'],'A','DETAIL','“I get up at six thirty.”'),
mc('How does Ben go to school?',['By car.','On foot.','By bicycle.','By bus.'],'D','DETAIL','“I take the bus to school.”'),
mc('When do his lessons begin?',['At seven thirty.','At eight.','At nine.','At eight thirty.'],'B','DETAIL','“My first lesson starts at eight.”'),
mc('Where does Ben have lunch?',['At home.','In a park.','At school.','In a restaurant.'],'C','DETAIL','“At twelve, I have lunch at school.”'),
mc('What does Ben do after dinner?',['Watches television.','Plays football.','Goes shopping.','Does his homework.'],'D','DETAIL','“After dinner, I do my homework.”')],script=[('Daniel',"""Hello, my name is Ben. I am a student. On weekdays, I get up at six thirty. I have bread and milk for breakfast. At seven fifteen, I take the bus to school. My first lesson starts at eight. At twelve, I have lunch at school with my friends. Classes finish at three in the afternoon. I go home and play with my dog. My family has dinner at six thirty in the evening. After dinner, I do my homework. I read a short story before bed. I go to bed at ten. My weekends are different, but this is my usual school day.""")],teaching='Đọc trước 5 câu hỏi, chú ý giờ và hoạt động. Nghe một lần để hiểu lịch chung, lần hai để kiểm tra chi tiết. get up = thức dậy; weekdays = ngày trong tuần.',rate=115)

add(5,59,'03_doc_lich_thong_bao','Đọc lịch và thông báo','READING','BEGINNER','Tìm ngày, giờ, địa điểm và yêu cầu trong thông báo ngắn.',
"""GREEN COMMUNITY CENTRE — ENGLISH CLUB
The English Club meets every Tuesday from 6:00 to 7:00 p.m. in Room 3. The first meeting this month is on 6 May. The club is for adults who want to practise simple English. Students can join too, but children under twelve cannot attend. Please bring a notebook and a pen. You do not need to bring a textbook. Joining the club is free. Water is available in the room. To join, send your name to Ms Hoa by email before Monday evening. The centre opens at 5:30 p.m., so you can arrive early. The Saturday art class takes place in Room 2 and is a different activity.""",[
mc('On which day does the English Club meet?',['Monday','Tuesday','Saturday','Sunday'],'B','DETAIL','“Every Tuesday” là lịch English Club; Saturday là lớp mỹ thuật.'),
mc('Where does the club meet?',['Room 2','The library','Room 3','The garden'],'C','DETAIL','Thông báo ghi “in Room 3”.'),
mc('What should participants bring?',['A notebook and a pen.','A textbook and water.','A laptop.','An art book.'],'A','DETAIL','“Please bring a notebook and a pen.”'),
mc('How much does joining cost?',['Five dollars.','Ten dollars.','Twenty dollars.','Nothing.'],'D','DETAIL','“Joining the club is free.”'),
mc('What should someone do to join?',['Call on Tuesday.','Visit Room 2.','Email Ms Hoa before Monday evening.','Send a textbook.'],'C','DETAIL','“Send your name to Ms Hoa by email before Monday evening.”')],teaching='Tìm từ khóa ngày/giờ/phòng. Không lấy thông tin của hoạt động khác. attend = tham dự; available = có sẵn.')

add(2,60,'01_doc_thuc_don','Đọc thực đơn và bảng giá','READING','BEGINNER','Tìm món, giá và giờ phục vụ trong thực đơn.',
"""SUN CAFE
We open from 8 a.m. to 5 p.m., Monday to Saturday. We are closed on Sunday.
Breakfast is served until 11 a.m.: egg sandwich — $4; fruit bowl — $3.
Lunch is served from 11 a.m. to 3 p.m.: chicken rice — $7; vegetable noodles — $6.
Drinks are available all day: tea — $2; coffee — $3; orange juice — $4. Tea can be hot or cold.
The vegetable noodles contain no meat. If you cannot eat eggs, please tell us before ordering. You can eat inside or take your food away. Card payment is accepted for orders of $5 or more. Free drinking water is available near the counter.""",[
mc('When is the cafe closed?',['Monday','Friday','Saturday','Sunday'],'D','DETAIL','“We are closed on Sunday.”'),
mc('How much is a fruit bowl?',['$2','$3','$4','$6'],'B','DETAIL','“Fruit bowl — $3.”'),
mc('Which lunch has no meat?',['Chicken rice.','Egg sandwich.','Vegetable noodles.','Coffee.'],'C','DETAIL','“The vegetable noodles contain no meat.”'),
mc('Until what time is breakfast served?',['11 a.m.','Noon','3 p.m.','5 p.m.'],'A','DETAIL','“Breakfast is served until 11 a.m.”'),
mc('How much are chicken rice and tea together?',['$7','$8','$10','$9'],'D','DETAIL','Chicken rice $7 cộng tea $2 bằng $9.')],teaching='Đối chiếu đúng món với giá. Nếu hỏi tổng tiền, cộng các giá được nêu. served = được phục vụ; closed = đóng cửa.')

add(2,61,'02_doc_tin_nhan','Đọc tin nhắn hẹn gặp','READING','BEGINNER','Xác định lịch hẹn và thay đổi qua tin nhắn.',
"""Linh, 9:00 a.m.: Hi Sam. Would you like to meet at the City Library on Friday? We can study English at 4 p.m.
Sam, 9:10 a.m.: I finish work at 4:30. Can we meet at 5 p.m. instead?
Linh, 9:15 a.m.: Yes, 5 p.m. is fine. The library closes at six, so we have one hour. Please bring your English notebook.
Sam, 9:20 a.m.: Great. Should I bring some snacks?
Linh, 9:25 a.m.: No, food is not allowed inside. Let's meet at the main entrance, beside the big clock.
Sam, 9:30 a.m.: OK. I will take the bus. See you on Friday.""",[
mc('On which day will they meet?',['Thursday','Friday','Saturday','Sunday'],'B','DETAIL','Tin đầu đề xuất Friday, tin cuối xác nhận Friday.'),
mc('What is the final meeting time?',['4 p.m.','4:30 p.m.','5 p.m.','6 p.m.'],'C','DETAIL','Sam đề xuất 5 p.m.; Linh xác nhận.'),
mc('Where will they meet first?',['At the main entrance.','In a cafe.','At a bus stop.','At work.'],'A','DETAIL','“At the main entrance, beside the big clock.”'),
mc('What should Sam bring?',['Snacks.','A clock.','A work report.','His English notebook.'],'D','DETAIL','Linh yêu cầu English notebook và nói không mang thức ăn.'),
mc('Why do they have only one hour?',['Sam starts work at six.','The library closes at six.','The bus leaves at six.','Linh has dinner at five.'],'B','DETAIL','Hẹn 5 p.m., thư viện đóng 6 p.m.')],teaching='Đọc toàn bộ tin nhắn để tìm lịch cuối cùng, không dừng ở đề xuất đầu. instead = thay vào đó; entrance = lối vào.')

add(2,62,'03_nghe_goi_mon','Nghe gọi món','LISTENING','BEGINNER','Nghe món, số lượng và giá trong tình huống gọi món.','Ordering lunch',[
mc('What food does the customer order?',['Two chicken sandwiches.','One cheese sandwich.','Two cheese sandwiches.','One chicken sandwich.'],'C','DETAIL','Khách nói “Two cheese sandwiches, please”.'),
mc('What drink does the customer choose?',['Hot tea.','Cold tea.','Coffee.','Orange juice.'],'B','DETAIL','Khách chọn “Cold tea, please.”'),
mc('How much does one sandwich cost?',['Two dollars.','Three dollars.','Six dollars.','Eight dollars.'],'B','DETAIL','Nhân viên: “Each sandwich is three dollars”.'),
mc('What is the total price?',['Five dollars.','Six dollars.','Seven dollars.','Eight dollars.'],'D','DETAIL','Hai sandwich $6, tea $2; nhân viên xác nhận total $8.'),
mc('Where will the customer eat?',['Outside in the park.','At home.','Inside the cafe.','At school.'],'C','DETAIL','Khách trả lời “Inside, please”.')],script=[('Daniel','Welcome to Oak Cafe. What would you like for lunch?'),('Samantha','Two cheese sandwiches, please. I do not want chicken today.'),('Daniel','Of course. Would you like a drink? We have coffee, tea and orange juice.'),('Samantha','One tea, please.'),('Daniel','Would you like hot tea or cold tea?'),('Samantha','Cold tea, please. How much is everything?'),('Daniel','Each sandwich is three dollars. The tea is two dollars. Your total is eight dollars.'),('Samantha','Here you are.'),('Daniel','Thank you. Will you eat here or take the food away?'),('Samantha','Inside, please. I am waiting for my friend.')],teaching='Nghe món được chọn, số lượng và tổng tiền. Những món được giới thiệu chưa chắc là món khách gọi.',rate=115)

add(9,63,'01_doc_email_chuyen_di','Đọc email về chuyến đi','READING','BEGINNER','Hiểu sự kiện và trình tự trong email về chuyến đi.',
"""Hi Lucy,
Last Saturday, my brother and I visited a small town near the sea. We left home at eight and travelled by train. The trip took two hours. First, we walked to the beach. It was sunny, but the water was cold, so we did not swim. At noon, we ate fish and rice at a small restaurant. After lunch, we visited a local museum. I bought a postcard there, but my brother did not buy anything. We wanted to stay until evening. However, it started raining at four, so we took an earlier train home. I enjoyed the museum most because I learned about the town's history. Next month, I hope to go back with you.
Best,
Tom""",[
mc('Who travelled with Tom?',['Lucy.','His brother.','His teacher.','His parents.'],'B','DETAIL','“My brother and I” đi cùng nhau.'),
mc('How did they travel?',['By car.','By bus.','By bicycle.','By train.'],'D','DETAIL','“Travelled by train.”'),
mc('What did they do after lunch?',['Swam.','Went home.','Visited a museum.','Bought fish.'],'C','DETAIL','“After lunch, we visited a local museum.”'),
mc('Why did they return early?',['It started raining.','The museum closed at noon.','Tom was ill.','They missed lunch.'],'A','DETAIL','“It started raining at four, so we took an earlier train home.”'),
mc('What did Tom enjoy most?',['Swimming.','The restaurant.','The train.','The museum.'],'D','DETAIL','“I enjoyed the museum most.”')],teaching='Chú ý first, after lunch, so để theo dõi trình tự. Phân biệt điều đã làm với điều muốn làm nhưng không thực hiện.')

add(9,64,'02_nghe_ke_hoach_cuoi_tuan','Nghe kế hoạch cuối tuần','LISTENING','BEGINNER','Theo dõi lựa chọn và xác định kế hoạch cuối cùng.','Planning Saturday',[
mc('Why do they decide not to play football?',['The park is closed.','It may rain.','They have no ball.','They must work.'],'B','DETAIL','Maya nói “The weather report says it may rain.”'),
mc('Which activity do they choose?',['Swimming.','A picnic.','A museum visit.','Football.'],'C','DETAIL','Cuối cùng chọn city museum.'),
mc('When will they meet?',['At ten.','At nine.','At eleven.','At twelve.'],'A','DETAIL','“How about ten?” được Maya đồng ý.'),
mc('Where will they meet?',['At the museum entrance.','At Maya\'s home.','In the park.','At the bus stop near school.'],'D','DETAIL','Leo nói bus stop near school; Maya xác nhận.'),
mc('What will Maya bring?',['Lunch.','A camera.','An umbrella.','A football.'],'B','DETAIL','Maya nói “I will bring my camera”.')],script=[('Daniel','Maya, shall we play football in the park on Saturday?'),('Samantha','I would like to, Leo, but the weather report says it may rain.'),('Daniel','Then we need an indoor activity. We could go swimming.'),('Samantha','The pool is closed this weekend. What about the city museum? There is a new photo exhibition.'),('Daniel','That sounds good. Can we meet at nine?'),('Samantha','I have breakfast with my grandmother at nine.'),('Daniel','How about ten? We can meet at the bus stop near school.'),('Samantha','Ten is fine. Yes, the bus stop near school. I will bring my camera.'),('Daniel','Great. I will bring some money for the tickets. See you on Saturday.')],teaching='Gạch chân các phương án khi đọc câu hỏi; chỉ chọn phương án hai người thống nhất cuối cùng.',rate=120)

add(9,65,'03_doc_quy_dinh','Đọc quy định nơi công cộng','READING','BEGINNER','Hiểu điều được phép, bị cấm và cần thực hiện trong quy định.',
"""RIVER LIBRARY — VISITOR RULES
The library opens at 9 a.m. and closes at 6 p.m. Please speak quietly. You may use your phone to read or send messages, but phone calls must be made outside. Food is not allowed. You can bring water in a bottle with a lid. Visitors may borrow up to three books at a time. Books must be returned within fourteen days. To borrow books, show your library card at the front desk. If you do not have a card, ask a member of staff for a registration form. Children under ten must stay with an adult. Computers are available on the first floor. Please book a computer before using it.""",[
mc('Where should visitors make phone calls?',['At the front desk.','On the first floor.','Outside.','Anywhere inside.'],'C','DETAIL','“Phone calls must be made outside.”'),
mc('Which drink container is allowed?',['A bottle with a lid.','An open cup of coffee.','An open glass.','No container at all.'],'A','DETAIL','“Water in a bottle with a lid.”'),
mc('How many books may a visitor borrow at once?',['One.','Two.','Five.','Three.'],'D','DETAIL','“Up to three books at a time.”'),
mc('When must borrowed books be returned?',['Within seven days.','Within fourteen days.','Within a month.','By six today.'],'B','DETAIL','“Within fourteen days.”'),
mc('What must visitors do before using a computer?',['Buy a card.','Bring food.','Book it.','Call outside.'],'C','DETAIL','“Please book a computer before using it.”')],teaching='may = được phép; must = bắt buộc; not allowed = không được phép. Tìm đúng quy định cho từng hành động.')

add(10,66,'01_nguyen_nhan_doi_lap','Hiểu quan hệ nguyên nhân và đối lập','READING','INTERMEDIATE','Nhận diện nguyên nhân, kết quả và quan hệ đối lập.',
"""A DIFFERENT WAY TO START THE DAY
Westfield School moved its first lesson from 7:30 to 8:15 after students reported feeling tired in early classes. Because many students travelled a long way, the old timetable required them to wake up before six. The later start gives them more time to sleep. Teachers have noticed fewer late arrivals, although they have not yet measured changes in exam scores.
The change also created a problem. Lessons now finish forty-five minutes later, so some students miss the bus they previously used. The school therefore arranged a new afternoon bus service. This solved the transport problem for most students, but the service costs money. To keep the cost manageable, the school shares the bus with a nearby college.
Some parents initially opposed the new timetable because it affected family routines. However, a survey after six weeks found that most parents now preferred it. The head teacher says the school will keep the new schedule for one term and review it before making a permanent decision. The school does not claim that later starts improve every aspect of learning; its current evidence concerns attendance and tiredness.""",[
mc('Why did the school change the start time?',['Students requested shorter holidays.','Students felt tired early in the day.','Teachers wanted fewer lessons.','The afternoon bus was free.'],'B','DETAIL','“After students reported feeling tired in early classes.”'),
mc('What does “although” introduce in the first paragraph?',['The reason for buying a bus.','A second start time.','A limitation of the available evidence.','An instruction to parents.'],'C','ARGUMENT','Có ít học sinh đến muộn, nhưng chưa đo thay đổi điểm thi.'),
mc('Why was a new afternoon bus arranged?',['The new finish time made some students miss their old bus.','All parents refused to drive.','The college moved away.','Students stopped attending school.'],'A','ARGUMENT','Kết thúc muộn hơn → lỡ bus cũ → dịch vụ mới.'),
mc('What contrast does “However” signal?',['Teachers versus students.','Morning versus afternoon lessons.','Bus price versus exam scores.','Initial parental opposition versus later support.'],'D','ARGUMENT','Ban đầu phụ huynh phản đối; khảo sát sau cho thấy phần lớn thích lịch mới.'),
mc('Which claim is supported by current evidence?',['Every student has higher scores.','There are fewer late arrivals.','The service costs nothing.','The decision is already permanent.'],'B','DETAIL','Teachers noticed fewer late arrivals; chưa có bằng chứng về điểm thi.')],teaching='because chỉ nguyên nhân; so/therefore chỉ kết quả; although/however chỉ đối lập. Đọc cả hai vế trước khi chọn.')

add(10,67,'02_nghe_paraphrase','Nhận diện diễn đạt tương đương','LISTENING','INTERMEDIATE','Nhận diện diễn đạt tương đương trong thông tin nghe.','Community centre announcement',[
mc('Which statement matches the announcement about membership?',['Members must attend every day.','Membership is available only to students.','People can join without paying a membership fee.','Membership is half price.'],'C','PARAPHRASE','“There is no charge to become a member” = không mất phí thành viên.'),
mc('What are visitors asked to do about exercise classes?',['Reserve a place ahead of time.','Arrive without registering.','Bring their own teacher.','Pay for a whole year.'],'A','PARAPHRASE','“Put your name on the class list before the day” = đặt chỗ trước.'),
mc('What happens when a class is full?',['It is cancelled.','Everyone gets a refund.','More chairs are added.','Applicants can join a waiting list.'],'D','PARAPHRASE','“We record your name and contact you if a place becomes available” = waiting list.'),
mc('Which statement about borrowing equipment is correct?',['You may keep it overnight.','You must return it before leaving.','You must buy it.','You may lend it to a friend.'],'B','PARAPHRASE','“Hand it back before you go home” = trả trước khi rời đi.'),
mc('Who can help a new visitor choose an activity?',['Only other members.','A person at the information desk.','A bus driver.','Only the manager by email.'],'B','PARAPHRASE','“Speak to our reception team” tương đương người ở bàn thông tin.')],script=[('Daniel',"""Welcome to Brook Community Centre. There is no charge to become a member, although individual activities may have their own small fees. You do not need to visit every day. Choose activities that fit your schedule. If you want to attend an exercise class, put your name on the class list before the day of the lesson. Some classes are popular and places are limited. When a class is full, we record your name and contact you if a place becomes available. You can borrow sports equipment while you are here. Please hand it back before you go home; equipment cannot be taken away overnight. If you are not sure which activity would suit you, speak to our reception team. They can explain what each class involves and help you find a suitable starting point. We hope you enjoy your first visit.""")],teaching='Câu hỏi thường dùng từ khác audio. Ví dụ “no charge” = “free”; chọn ý tương đương, không chỉ từ giống nhau.',rate=140)

add(10,68,'03_doan_nghia_tu','Đoán nghĩa từ trong ngữ cảnh','READING','INTERMEDIATE','Dùng ngữ cảnh để hiểu từ và cụm từ mới.',
"""THE REPAIR CLUB
At the town's monthly repair club, volunteers help residents fix broken household objects. The organisers want to reduce waste rather than encourage people to buy replacements. A damaged chair or a lamp with a loose wire may still be useful after a simple repair. Residents are asked to bring only portable items: objects that one person can carry safely. Large refrigerators are not accepted.
The volunteers diagnose a problem before attempting a repair. They examine the object, ask when it stopped working and decide what may be wrong. Their service is free, but residents can make a voluntary donation if they wish. Nobody is required to give money.
The club also teaches basic maintenance. Cleaning a filter regularly, for example, can prevent a machine from breaking down. The organisers describe repair as a collaborative activity: the owner works alongside a volunteer instead of leaving the object and collecting it later. This helps residents learn skills they can use again.
Not every item can be repaired. If an object is unsafe or a necessary part is unavailable, volunteers explain the problem and suggest responsible recycling. The club's goal is not to save every object at any cost, but to help people make informed decisions about repair and replacement.""",[
mc('What does “portable” mean here?',['Easy to carry.','Very expensive.','Made of metal.','Newly purchased.'],'A','DETAIL','Ngay sau từ có giải thích “objects that one person can carry safely”.'),
mc('What does “diagnose” mean here?',['Sell an object.','Clean an object.','Identify what is wrong.','Replace every part.'],'C','DETAIL','Volunteers examine, ask và decide what may be wrong.'),
mc('What does “voluntary” tell us about donations?',['They are paid monthly.','They are optional.','They are large.','They are a repair charge.'],'B','DETAIL','“Nobody is required to give money.”'),
mc('What is “maintenance” in this passage?',['Buying a new machine.','Taking a machine apart once.','Throwing away a filter.','Regular care that helps prevent problems.'],'D','DETAIL','Ví dụ cleaning a filter regularly để prevent breakdown.'),
mc('What does “collaborative” mean here?',['Done in secret.','Done without the owner.','Done by people working together.','Done only by professionals.'],'C','DETAIL','“The owner works alongside a volunteer”.')],teaching='Tìm định nghĩa, ví dụ hoặc câu giải thích gần từ mới. Không đoán chỉ theo hình thức của từ.')

add(4,69,'01_doc_email_cong_viec','Đọc email công việc','READING','INTERMEDIATE','Xác định yêu cầu, người phụ trách và hạn hoàn thành trong email.',
"""Subject: Preparing for Thursday's client visit
Hello team,
Our visitors from Northbridge Design will arrive at 10 a.m. on Thursday. They want to see how we organise customer feedback, not a general presentation about every service we offer. Please keep the discussion focused on that topic.
Minh, could you prepare a short summary of the survey results? Include the three most common customer concerns and one example of how we responded to each. Please send your draft to me by noon on Wednesday so I can check the figures. You do not need to include customers' names or contact details.
Lan, please book Meeting Room B for 9:30 a.m. to noon on Thursday. We will use the first thirty minutes to check the projector and arrange the seats. The clients will not arrive until ten. If Room B is unavailable, let me know before choosing another room.
David, please print six copies of the final summary on Thursday morning. Wait until I confirm that Minh's draft is approved; printing an earlier version could confuse our visitors. There is no need to prepare gift bags.
Everyone attending should read the summary before the visit. We will finish the client discussion at eleven thirty, leaving time for questions before noon. If you cannot attend, tell me by Wednesday afternoon so I can arrange cover.
Thanks,
Sara, Project Coordinator""",[
mc('What is the main purpose of the visit?',['To discuss all company services.','To review customer feedback practices.','To recruit new staff.','To deliver gift bags.'],'B','MAIN_IDEA','Khách muốn xem cách organise customer feedback; không phải giới thiệu mọi dịch vụ.'),
mc('When must Minh send his draft?',['Thursday morning.','Wednesday afternoon.','Tuesday noon.','Wednesday noon.'],'D','DETAIL','“By noon on Wednesday.”'),
mc('Why is the room booked from 9:30?',['To prepare before visitors arrive.','The visitors arrive at 9:30.','To interview customers.','To print gift labels.'],'A','DETAIL','30 phút đầu dùng kiểm tra projector và xếp ghế.'),
mc('What must David wait for before printing?',['A new projector.','Six visitors to arrive.','Approval of the final summary.','Room B to become free.'],'C','DETAIL','“Wait until I confirm ... draft is approved.”'),
mc('Which information should Minh leave out?',['Customer concerns.','Response examples.','Survey figures.','Customers\' contact details.'],'D','DETAIL','Email nói không cần names or contact details.')],teaching='Đọc yêu cầu theo từng người; đánh dấu deadline và điều kiện “before/until”. Không nhầm giờ chuẩn bị với giờ khách đến.')

add(4,70,'02_nghe_sap_xep_cuoc_hop','Nghe sắp xếp cuộc họp','LISTENING','INTERMEDIATE','Theo dõi thay đổi giờ, phòng và xác định lịch cuối cùng.','Rescheduling a project meeting',[
mc('When will the meeting take place?',['Tuesday at nine.','Wednesday at ten.','Wednesday at nine.','Tuesday at ten.'],'B','CORRECTION','Tuesday bị bỏ; Wednesday at ten được xác nhận.'),
mc('Where will the meeting be held?',['Room A.','Online only.','Room C.','Room B.'],'C','CORRECTION','Room B đang sửa; chuyển sang Room C.'),
mc('Why can they not use Room B?',['It is being repaired.','It has no chairs.','It is too small.','The client booked it.'],'A','DETAIL','“Maintenance team will be working in Room B”.'),
mc('What should Alex bring?',['A printed contract.','A gift for the client.','A room key.','The revised cost estimate.'],'D','DETAIL','“Bring the revised cost estimate”.'),
mc('How long is the meeting expected to last?',['Thirty minutes.','One hour.','Two hours.','Ninety minutes.'],'B','DETAIL','“From ten until eleven”.')],script=[('Samantha','Alex, I need to change our project meeting. We originally planned Tuesday at nine, but the client is travelling that morning.'),('Daniel','Could we move it to Wednesday at nine?'),('Samantha','The client has another appointment until half past nine. Wednesday at ten would work.'),('Daniel','Ten is fine for me. Will we still use Room B?'),('Samantha','No. The maintenance team will be working in Room B. I have booked Room C instead. It has the same projector, so your presentation should work there.'),('Daniel','Should I bring the original budget or the new estimate?'),('Samantha','Bring the revised cost estimate. We need to discuss the changes, not approve the old version. You can show it on screen; printed copies are not necessary.'),('Daniel','How much time have we allowed?'),('Samantha','From ten until eleven. After that, Room C is booked for another team.'),('Daniel','So that is Wednesday at ten, in Room C, for one hour. I will bring the revised estimate.'),('Samantha','Exactly. I will send everyone an updated invitation this afternoon.')],teaching='Ghi nhận đề xuất đầu rồi cập nhật khi nghe instead/no/revised. Lời nhắc cuối thường xác nhận lịch đã thống nhất.',rate=145)

add(4,71,'03_doc_de_xuat_cai_thien','Đọc đề xuất cải thiện công việc','READING','INTERMEDIATE','Xác định vấn đề, giải pháp và lý do trong đề xuất công việc.',
"""PROPOSAL: A SHARED HANDOVER NOTE
Our support team works in two shifts. At present, staff leaving the morning shift usually explain unfinished cases verbally to the afternoon team. This works when both teams are available at the same time. However, calls sometimes delay the conversation, and important details can be forgotten. Last month, three customers had to describe the same problem again because the second team did not have a clear record.
I propose using a short shared handover note for every unresolved case. The note would contain the case number, the customer's main issue, actions already taken and the next step. It would not include unnecessary personal information. The morning team would complete it before leaving, and the afternoon team would read it before contacting the customer.
This is not a proposal for a new software purchase. We can use a secure system the company already provides. The main cost would be the time needed to write the note. To keep that time reasonable, the template should fit on one screen and use short headings.
We should trial the process for two weeks. During the trial, we can count cases where customers repeat information and ask staff whether the notes are useful. If the notes reduce repetition without creating too much work, we can keep the process. If not, we should simplify the template before extending it to other teams. A successful trial would improve continuity between shifts, but it would not replace conversations when a case is complicated.""",[
mc('What problem is the proposal trying to solve?',['A shortage of computers.','Expensive new software.','Loss of information between shifts.','Too many staff meetings.'],'C','MAIN_IDEA','Chi tiết handover bị quên làm khách phải nhắc lại vấn đề.'),
mc('What is the proposed solution?',['A short shared note for unresolved cases.','A longer lunch break.','A new public website.','Ending the afternoon shift.'],'A','DETAIL','“Short shared handover note for every unresolved case”.'),
mc('What does “continuity between shifts” mean here?',['Making both shifts equally long.','Keeping the same staff all day.','Avoiding all customer calls.','Allowing the next team to continue with the right information.'],'D','PARAPHRASE','Note lưu actions và next step để ca sau tiếp tục đúng việc.'),
mc('How will the trial be evaluated?',['By counting all emails only.','By measuring repeated information and asking staff for feedback.','By buying software.','By removing complex cases.'],'B','DETAIL','Đếm khách phải repeat information và hỏi staff về usefulness.'),
mc('What limitation does the author acknowledge?',['Notes cannot contain case numbers.','The company has no secure system.','Complex cases may still require conversation.','The trial cannot be changed.'],'C','ARGUMENT','“Would not replace conversations when a case is complicated”.')],teaching='Tìm ba phần: vấn đề, giải pháp, cách kiểm tra giải pháp. Phân biệt đề xuất đang thử với kết luận đã được chứng minh.')

add(11,72,'01_reading_paraphrase','Reading: Paraphrase và thông tin chi tiết','READING','INTERMEDIATE','Đối chiếu câu hỏi với bằng chứng được diễn đạt bằng từ khác.',
"""LEARNING BEYOND THE LECTURE
At Eastport College, students on an introductory science course used to attend two long lectures each week. Most information came from the teacher, while students listened and took notes. A recent pilot replaced one lecture with a problem-solving workshop. Students still attended the other lecture, so the course did not remove teacher explanations entirely.
Before each workshop, students watched a short video and answered three preparation questions. In class, they worked in groups of four to solve a practical problem. The teacher moved between groups, asked questions and clarified misunderstandings. Students were expected to explain their reasoning, rather than simply copy a correct answer.
The first workshops were not immediately successful. Some students arrived without watching the video and depended on classmates to explain the background. In response, the teacher made the preparation questions part of the workshop's opening activity. This encouraged students to prepare and gave the teacher a quick indication of what needed explanation.
After eight weeks, participating students performed better on a task requiring them to apply ideas to an unfamiliar situation. Their scores on a factual recall test were similar to those of a previous class. The organisers therefore suggest that the workshops may help application more than memorisation. They also note that the classes were not randomly assigned, so the difference cannot be attributed to the teaching format alone.
Students reported that speaking in small groups felt less intimidating than asking questions in a large lecture hall. However, some wanted clearer roles within groups because one confident student sometimes dominated discussion. The college plans to keep the workshops while testing a system in which students rotate the roles of explaining, checking and recording. The pilot supports further investigation, rather than a claim that lectures should disappear.""",[
mc('How did the pilot change the weekly timetable?',['It removed both lectures.','It added four lectures.','It replaced all teacher explanations.','It exchanged one lecture for a workshop.'],'D','PARAPHRASE','“Replaced one lecture” = đổi một lecture thành workshop; vẫn giữ lecture còn lại.'),
mc('What were students required to do before workshops?',['Write a long essay.','Watch a video and answer preparation questions.','Meet the teacher individually.','Memorise every group answer.'],'B','DETAIL','Đoạn hai nêu short video + three preparation questions.'),
mc('Which result improved?',['Using ideas in a new situation.','Remembering facts on the recall test.','Attendance at every lecture.','Random assignment of classes.'],'A','PARAPHRASE','“Apply ideas to an unfamiliar situation” = sử dụng ý tưởng trong tình huống mới.'),
mc('Why should the findings be interpreted cautiously?',['The workshops lasted only one day.','No tests were given.','The classes were not randomly assigned.','Every student disliked the workshop.'],'C','DETAIL','Không phân nhóm ngẫu nhiên nên không quy kết khác biệt chỉ cho teaching format.'),
mc('What is the main message of the passage?',['Lectures have no purpose.','Every group should have one permanent leader.','Preparation is unnecessary.','Workshops show potential, but their design and evidence need further work.'],'D','MAIN_IDEA','Tác giả ghi nhận lợi ích, hạn chế và kế hoạch cải thiện, không đòi xóa lectures.')],teaching='Paraphrase giữ nguyên ý, không nhất thiết cùng từ. Chú ý mức khẳng định may/cannot/alone để tránh chọn đáp án phóng đại.')

add(11,73,'02_listening_sua_thong_tin','Listening: Nhận diện thông tin được sửa lại','LISTENING','INTERMEDIATE','Phân biệt thông tin ban đầu với thông tin được xác nhận cuối cùng.','Booking a workshop place',[
mc('On which day is the booking finally made?',['Friday.','Saturday.','Sunday.','Monday.'],'C','CORRECTION','Saturday đã đầy; Sunday được khách chọn.'),
mc('What is the confirmed starting time?',['9:30 a.m.','10 a.m.','10:30 a.m.','11 a.m.'],'B','CORRECTION','Khách hỏi 9:30; nhân viên sửa thành ten.'),
mc('What will the customer pay?',['Twenty pounds.','Fifteen pounds.','Twenty-five pounds.','Ten pounds.'],'B','CORRECTION','Phí thường £20; student discount còn £15.'),
mc('Where should the customer go?',['Room 4 on the ground floor.','Room 2 on the first floor.','Room 4 on the first floor.','Room 2 on the ground floor.'],'D','CORRECTION','Room 4 đang được dùng; địa điểm cuối là Room 2 ground floor.'),
mc('What must the customer bring to receive the discount?',['A notebook.','A printed email.','A student card.','A camera.'],'C','DETAIL','Cần student card để kiểm tra eligibility for reduced fee.')],script=[('Samantha','Hello. I would like to book the photography workshop on Saturday.'),('Daniel','Saturday is already full. We have places on Sunday, though.'),('Samantha','Sunday works for me. Does it begin at nine thirty, like the poster says?'),('Daniel','That poster shows the old schedule. The Sunday workshop starts at ten and finishes at twelve.'),('Samantha','I see. And the price is twenty pounds?'),('Daniel','That is the standard fee. If you are a student, the fee is fifteen pounds.'),('Samantha','I am a college student, so I would like the student rate.'),('Daniel','Certainly. Please bring your student card so we can check it when you arrive.'),('Samantha','Will it be in Room four upstairs?'),('Daniel','We have changed the room as well. Another group is using Room four. Your workshop is in Room two on the ground floor, near reception.'),('Samantha','Should I bring a professional camera?'),('Daniel','No. A phone camera is enough for the activities. A notebook may be useful, but it is not required.'),('Samantha','Let me check: Sunday at ten, Room two on the ground floor, fifteen pounds with my student card.'),('Daniel','That is correct. I will email your confirmation today.')],teaching='Các số hoặc địa điểm đầu tiên có thể là thông tin cũ. Nghe old/changed/standard/student rate và lời xác nhận cuối.',rate=145)

add(7,75,'01_reading_quan_diem_suy_luan','Reading: Quan điểm và suy luận','READING','ADVANCED','Suy luận từ bằng chứng và phân biệt quan điểm tác giả với ý kiến được dẫn.',
"""WHEN A DASHBOARD LOOKS LIKE LEARNING
Schools increasingly use digital dashboards to monitor students' activity. A dashboard may display minutes spent on a platform, completed exercises and the number of correct answers. Supporters argue that such information helps teachers notice a struggling student before a final examination. This is a reasonable possibility, but a visible measure should not automatically be treated as a complete description of learning.
Consider time on a platform. A student may leave a page open while doing something unrelated, producing a long session without sustained attention. Another student may understand a task quickly and finish in a short session. The first record looks more impressive if duration is the only measure, although the second student may have learned more efficiently. Time can be useful context, but its meaning depends on what the student was doing.
Completion counts have similar limitations. Repeating familiar exercises may produce many completed tasks without requiring new understanding. Conversely, working carefully through one unfamiliar problem can involve substantial learning. A system that rewards completion alone may unintentionally encourage students to choose easy work. This does not make completion data worthless; it means that the difficulty and purpose of tasks must also be considered.
Some technology companies respond by combining many indicators into a single progress score. A combined score can simplify communication, but it can also conceal assumptions. If a system gives more weight to speed than to explanation, a thoughtful student may appear less successful. Teachers and students should therefore be able to ask what a score represents and which behaviours increase it. A number is easier to display than a complex explanation, yet ease of display is not evidence of validity.
The strongest use of dashboards is arguably as a starting point for inquiry. If a student's accuracy falls, a teacher can inspect the tasks and ask the student to explain an answer. An error might reflect a misunderstood concept, unfamiliar vocabulary or simply an accidental selection. These possibilities require different responses, even when the recorded outcome is identical. Data can help direct attention, while conversation and fresh assessment help interpret it.
None of this requires abandoning educational technology. The problem is not measurement itself but the temptation to make claims beyond what a measure supports. Schools can report that a learner completed a practice activity without claiming that the learner has mastered the underlying skill. They can also test understanding with unfamiliar questions after a delay. A dashboard designed around those distinctions is less dramatic than one promising to reveal learning instantly, but it is more useful for decisions about what to teach next.""",[
mc('What is the author\'s central position?',['All educational technology should be removed.','Dashboard measures require interpretation before they support learning claims.','Long sessions always show deep learning.','Teachers should ignore recorded errors.'],'B','MAIN_IDEA','Bài phân tích giới hạn dữ liệu và đề xuất dùng dữ liệu làm điểm khởi đầu cho kiểm tra thêm.'),
mc('What can be inferred from the comparison of two students\' session lengths?',['Quick students never need help.','Long sessions are always dishonest.','Duration alone may rank learning misleadingly.','Task difficulty never affects completion.'],'C','INFERENCE','Một người mở trang nhưng không tập trung; người khác hiểu nhanh. Thời lượng không đủ xếp năng lực.'),
mc('Which view is attributed to supporters of dashboards?',['They can help identify difficulty before a final exam.','They prove mastery instantly.','They should replace every conversation.','They contain no useful information.'],'A','AUTHOR_ATTITUDE','Đoạn đầu gán “notice a struggling student before a final examination” cho supporters; tác giả chỉ thừa nhận possibility.'),
mc('Why does the author question a single combined progress score?',['It necessarily contains arithmetic errors.','Students cannot read numbers.','It makes all tasks harder.','Its weighting can hide assumptions about successful learning.'],'D','ARGUMENT','Đoạn bốn: score có thể conceal assumptions, như coi trọng speed hơn explanation.'),
mc('Which action best follows the author\'s recommendation after accuracy falls?',['Immediately label the student incapable.','Inspect the tasks and ask for an explanation.','Delete all prior records.','Give only the easiest tasks.'],'B','INFERENCE','Đoạn năm đề xuất inspect tasks và ask student, vì các nguyên nhân sai khác nhau.')],teaching='Phân biệt supporters argue với quan điểm của tác giả. Đáp án suy luận phải có bằng chứng, không thêm kết luận tuyệt đối như always/instantly.')

add(7,76,'02_listening_theo_doi_lap_luan','Listening: Theo dõi lập luận','LISTENING','ADVANCED','Theo dõi lập luận, giới hạn bằng chứng và thái độ của người nói.','A pilot study on study spaces',[
mc('What question did the pilot investigate?',['Whether students preferred online exams.','Whether libraries should close.','Whether different study spaces affected work on a new problem.','Whether music improved every student\'s memory.'],'C','MAIN_IDEA','Pilot so sánh study spaces khi giải unfamiliar problem.'),
mc('Why can the researchers not claim that the quiet room caused better performance?',['Students chose their own room.','The room had no furniture.','No student finished the task.','The researchers counted only books.'],'A','ARGUMENT','Self-selection có thể phản ánh khác biệt motivation/background trước khi vào phòng.'),
mc('What did the speaker observe about discussion?',['It prevented all concentration.','It was always irrelevant.','It replaced written answers.','It sometimes revealed a misunderstanding.'],'D','DETAIL','Một peer question khiến student nhận ra hiểu sai task.'),
mc('How does the speaker regard the initial results?',['As decisive proof.','As promising but preliminary.','As completely useless.','As evidence against all group study.'],'B','AUTHOR_ATTITUDE','“Encouraging ... not a final verdict”; bằng chứng ban đầu cần thử thêm.'),
mc('Which next step is proposed?',['Let each student select a room again without recording it.','Stop measuring task difficulty.','Assign spaces more systematically and compare similar tasks.','Replace every quiet room with a cafe.'],'C','ARGUMENT','Đề xuất assign spaces more systematically và comparable tasks để xử lý giới hạn.')],script=[('Daniel',"""Today I want to explain a small pilot study, rather than announce a universal rule about studying. We asked whether the space students used affected their work on an unfamiliar problem. One group worked in a quiet room, while another used a shared space where discussion was allowed. The students in the quiet room produced more complete individual answers on average. That result is interesting, but it does not prove that silence caused the difference. Students chose their own room. Those selecting the quiet space may already have been more motivated, or more familiar with the topic. We also observed something that an average score could easily hide. In the discussion space, one student's question helped a classmate notice that she had misunderstood the task. Her first answer was weak, but her explanation improved after the conversation. If we considered only her first written response, we would miss that change. Discussion was not helpful in every case: a few conversations drifted away from the task. So I would not recommend replacing all quiet rooms with group spaces. Equally, the results do not justify banning discussion. They suggest that different spaces may serve different stages of learning. A quiet room may help someone develop an individual answer, while a shared space may help test an interpretation. Our next study will assign spaces more systematically and use tasks of comparable difficulty. We will also ask students to explain their answers, not just count completed responses. I find the early results encouraging, but they are a starting point for better questions, not a final verdict about the best place to study.""")],teaching='Theo dõi claim → evidence → limitation → next step. Chú ý thái độ cautious/encouraging, không nhầm kết quả ban đầu với chứng minh nhân quả.',rate=160)

add(8,78,'01_reading_true_false_not_given','Reading: Phân biệt thông tin đúng, sai, không có','READING','ADVANCED','Phân biệt thông tin được xác nhận, bị phủ định và không được nêu.',
"""A LIBRARY OF THINGS
The Riverton Library of Things lends equipment that residents may need only occasionally, such as drills, sewing machines and camping lamps. The project began with a practical question: why should every household purchase an object that spends most of its life in a cupboard? Sharing can reduce unnecessary purchases, but the organisers also see the service as a way to make useful equipment accessible to residents who cannot easily afford it.
The service is open to adults living in the district. Members register online or at the desk and show proof of their address before their first loan. Most objects can be borrowed for seven days. A shorter three-day period applies to drills during busy weekends, allowing more people to use them. Members are told the return date when they collect an item. They are not expected to infer it from a general rule.
Every returned electrical item is inspected by a trained volunteer before it is lent again. The inspection checks basic safety and records visible damage. If an item needs repair, it is removed from the available list until the problem is resolved. This process takes time, so the number of objects physically present in the building may be larger than the number available to borrow. A full shelf does not necessarily mean a particular item can leave immediately.
The library charges a small annual membership fee, while ordinary borrowing is included. A separate charge may apply when a member returns an item damaged through misuse. The organisers say that ordinary wear is different from misuse, and staff discuss uncertain cases with members rather than imposing a charge automatically. The project has not published the average amount spent on repairs per month.
Some residents initially expected the service to eliminate demand for new household equipment. The organisers regard that expectation as unrealistic. A frequently used object may still be worth owning, especially when immediate access matters. They suggest borrowing before buying as one useful option: a resident can discover whether a tool suits a task before purchasing it. They do not claim that shared ownership is appropriate for every object or every household.
The project plans to evaluate both use and access. Loan counts reveal which items are popular, but the organisers will also ask whether members could complete tasks they otherwise could not afford. They want to know whether the service creates useful opportunities, not simply whether objects move in and out of the building. A large number of loans might represent genuine benefit, repeated borrowing by a small group, or both. Understanding the difference requires more than an impressive total.""",[
tf('A drill may have a shorter loan period than the usual seven days.','TRUE','Đoạn hai: drills during busy weekends có thời hạn three days.'),
tf('Every returned electrical item is immediately available for a new loan.','FALSE','Đoạn ba: phải inspected; item cần repair bị loại khỏi available list.'),
tf('The library has published its average monthly repair spending.','FALSE','Đoạn bốn nói rõ “has not published”. Đây là phủ định, không phải thiếu thông tin.'),
tf('Most members register online rather than at the desk.','NOT GIVEN','Có hai cách đăng ký nhưng không có số lượng hoặc tỷ lệ mỗi cách.'),
tf('The organisers believe loan counts alone are enough to evaluate the service.','FALSE','Đoạn cuối nói Understanding the difference requires more than ... total; cần đánh giá access.')],teaching='TRUE: cùng ý; FALSE: có bằng chứng trái ý; NOT GIVEN: thiếu dữ kiện để kết luận. Không dùng kiến thức ngoài bài. Với TRUE/FALSE/NOT GIVEN, viết đầy đủ như khuôn.')

add(8,79,'02_listening_ghep_nguoi_noi','Listening: Ghép ý với người nói','LISTENING','ADVANCED','Gán đúng ý kiến và thái độ cho từng người nói.','Three views of a mentoring programme',[
mc('Who says the programme clarified a realistic career path?',['Lena.','Omar.','Priya.','None of the speakers.'],'A','SPEAKER_MATCH','Lena hiểu responsibilities và realistic next step.'),
mc('Who criticises the timing of the sessions?',['Priya.','Lena.','All three speakers.','Omar.'],'D','SPEAKER_MATCH','Omar: sessions coincide with shift nên khó tham dự.'),
mc('Who values learning from other participants\' mistakes?',['Omar.','Lena.','Priya.','No speaker.'],'C','SPEAKER_MATCH','Priya học từ participants explain what had gone wrong.'),
mc('Who wants shorter follow-up conversations rather than one final meeting?',['Lena.','Omar.','Priya.','All three speakers.'],'B','SPEAKER_MATCH','Omar đề xuất brief follow-up conversations.'),
mc('Who warns against copying another person\'s career plan unchanged?',['Lena.','Omar.','No speaker.','Priya.'],'D','SPEAKER_MATCH','Priya: adapt advice to your own circumstances, không simply copy.')],script=[('Samantha',"""Speaker one, Lena. Before joining the mentoring programme, I had a rather vague idea of what a project coordinator did. My mentor described the daily responsibilities, including the less exciting administrative work. That helped me identify a realistic next step instead of applying for every job with an attractive title. I appreciated that she did not promise instant promotion. We discussed what I could practise in my current role. The programme was most useful when it turned a general ambition into a specific action."""),('Daniel',"""Speaker two, Omar. The mentor was helpful, but the organisation of the sessions made participation difficult. Several meetings coincided with my work shift, so attending required a change that my manager could not always approve. I would offer the same session at different times. I also think a single final meeting is less useful than brief follow-up conversations. Advice that sounds clear on the day can become confusing when you try to apply it. A short conversation two weeks later could help resolve those questions."""),('Karen',"""Speaker three, Priya. I expected most of the learning to come from the mentor, but I learned a great deal from other participants. Hearing someone explain what had gone wrong in an interview helped me notice a similar weakness in my own preparation. Still, I would not simply copy that person's career plan. People have different responsibilities and opportunities. The useful lesson is to adapt advice to your own circumstances. The programme gave us examples to think with, not a single route everyone must follow.""")],teaching='Ghi từ khóa theo từng người: Lena, Omar, Priya. Các câu hỏi hỏi ai giữ một ý kiến, không phải ai có tên xuất hiện gần từ khóa.',rate=155)

add(5,89,'04_cuoi_chang_reading','Reading — Kiểm tra cuối chặng Beginner','READING','BEGINNER','Kiểm tra đọc thông tin trực tiếp trong hồ sơ và thông báo mới.',
"""MEET PAUL
Paul is twenty-eight. He is a cook at a small hotel in Bristol. He lives with his cousin, Jack, who works in a bookshop. Paul starts work at two in the afternoon and finishes at ten at night. He goes to work by bicycle. On Mondays, his day off, he enjoys drawing at home.

HOTEL NOTICE
The hotel's beginner cooking class takes place on Sunday, from 10 a.m. to noon, in the ground-floor kitchen. Adults and teenagers aged sixteen or over can attend. Bring a small container to take your food home. Ingredients and cooking tools are provided. The class costs twelve pounds. Please book by Friday at the hotel reception. There is no class on Saturday.""",[
mc('What is Paul\'s job?',['Bookshop assistant.','Hotel receptionist.','Cook.','Art teacher.'],'C','DETAIL','Hồ sơ ghi “He is a cook”.'),
mc('How does Paul travel to work?',['By bicycle.','By train.','By bus.','On foot.'],'A','DETAIL','“By bicycle.”'),
mc('Which day is Paul\'s day off?',['Sunday.','Saturday.','Friday.','Monday.'],'D','DETAIL','“On Mondays, his day off”.'),
mc('When does the cooking class end?',['At ten in the morning.','At noon.','At two.','At ten at night.'],'B','DETAIL','Class 10 a.m. to noon; không lấy giờ làm của Paul.'),
mc('What must a participant bring?',['Ingredients.','Cooking tools.','A small container.','A bicycle.'],'C','DETAIL','“Bring a small container”; ingredients/tools được cung cấp.'),
mc('Where should someone book the class?',['At the bookshop.','In Paul\'s home.','At a bus stop.','At the hotel reception.'],'D','DETAIL','“Book by Friday at the hotel reception.”')],role='FINAL')

add(5,90,'05_cuoi_chang_listening','Listening — Kiểm tra cuối chặng Beginner','LISTENING','BEGINNER','Kiểm tra nghe giờ, địa điểm và hoạt động trong thông tin mới.','A new art class',[
mc('On which day is the class?',['Tuesday.','Wednesday.','Thursday.','Friday.'],'B','DETAIL','“Every Wednesday”.'),
mc('What time does the class start?',['At four.','At five.','At six.','At seven.'],'C','DETAIL','“From six to seven thirty in the evening”.'),
mc('In which room does it take place?',['Room four.','Room two.','Room six.','Room ten.'],'A','DETAIL','“Room four, next to the cafe”.'),
mc('What should students bring?',['Paints.','A chair.','An apron.','A pencil.'],'D','DETAIL','“Please bring a pencil”; paper and paints provided.'),
mc('How much does one class cost?',['Five pounds.','Eight pounds.','Ten pounds.','Twelve pounds.'],'B','DETAIL','“Eight pounds for each class”.'),
mc('How should a new student register?',['By email.','By buying paint.','By calling a school.','By visiting on Sunday.'],'A','DETAIL','“Send your name by email before Tuesday”.')],script=[('Samantha',"""Hello, this is a message about the new art class at Meadow Centre. The class meets every Wednesday, from six to seven thirty in the evening. We use Room four, next to the cafe. You do not need to be good at drawing to join. The teacher will help beginners. Please bring a pencil. Paper and paints are provided, so you do not need to buy them. The price is eight pounds for each class. You can pay at reception when you arrive. To register, send your name by email before Tuesday. Please arrive ten minutes early for your first lesson. We look forward to meeting you.""")],role='FINAL',rate=120)

add(11,91,'04_cuoi_chang_reading','Reading — Kiểm tra cuối chặng Intermediate','READING','INTERMEDIATE','Kiểm tra ý chính, paraphrase và liên hệ giữa các ý trong văn bản mới.',
"""A TRIAL OF SHARED BICYCLES
The town of Lakeford introduced a shared bicycle service for short journeys between the station, the college and the town centre. The council hoped that some people would choose a bicycle instead of driving for the final part of their journey. The service was not intended to replace buses on longer routes.
During the first month, bicycles had to be returned to the same station where they were collected. Users said this made one-way trips inconvenient. The council then allowed returns at any of the three official stations. This made the service more flexible, but it created a new difficulty: bicycles often accumulated at the college in the morning and were scarce near the railway station.
A small team now moves bicycles between stations twice a day. This adds an operating cost, so the council is also testing messages that tell users where bicycles are available. The messages may help people plan a trip, although they cannot guarantee that a bicycle will still be there on arrival.
Usage increased after the return rule changed. However, the council does not know how many users would otherwise have travelled by car. Some may have walked or taken a bus. It is therefore too early to claim that the service has reduced traffic by a particular amount.
A survey will ask users about their previous travel habits and whether they could find a bicycle when needed. The council also plans to record the time and location of unavailable bicycles. It wants to assess practical access as well as the total number of journeys. The trial will continue for three more months before a decision is made about adding further stations.""",[
mc('What is the main purpose of the service?',['To replace all buses.','To support short connecting journeys.','To close the railway station.','To sell bicycles to the college.'],'B','MAIN_IDEA','Đoạn đầu nêu short journeys/final part; không thay buses trên longer routes.'),
mc('Which statement paraphrases the new return rule?',['Users must go back to their starting point.','Users may leave bicycles anywhere.','Users may return bicycles at any official station.','Users must keep bicycles overnight.'],'C','PARAPHRASE','“Any of the three official stations” không có nghĩa bất kỳ nơi nào.'),
mc('What problem followed the rule change?',['Bicycles were unevenly distributed.','All users stopped cycling.','The college had no morning classes.','The railway station closed.'],'A','ARGUMENT','Bikes dồn ở college, scarce near station → phân bố không đều.'),
mc('Why cannot more journeys alone prove reduced car traffic?',['The bicycles have no wheels.','Every user previously drove.','The council records no journeys.','Some users may previously have walked or used buses.'],'D','ARGUMENT','Đoạn bốn phân biệt sử dụng dịch vụ và thực sự thay hành trình ô tô.'),
mc('What limitation applies to availability messages?',['They are only sent once a year.','Availability may change before arrival.','They never show station names.','They guarantee a reserved bicycle.'],'B','DETAIL','Messages không guarantee bike still there on arrival.'),
mc('What will the council evaluate besides journey totals?',['Users\' exam scores.','The colour of cars.','Whether users can obtain bicycles when needed.','The number of private houses.'],'C','PARAPHRASE','“Practical access” là có tìm được xe lúc cần.')],role='FINAL')

add(11,92,'05_cuoi_chang_listening','Listening — Kiểm tra cuối chặng Intermediate','LISTENING','INTERMEDIATE','Kiểm tra nghe chi tiết, paraphrase và thông tin thay đổi.','Booking a business communication course',[
mc('What day is the final booking for?',['Monday.','Tuesday.','Thursday.','Friday.'],'C','CORRECTION','Tuesday bị đầy; Thursday được xác nhận.'),
mc('What is the confirmed start time?',['6 p.m.','6:30 p.m.','7 p.m.','7:30 p.m.'],'B','CORRECTION','Trang web cũ 6; lịch mới 6:30.'),
mc('What room will be used?',['Room five.','Room three.','Room seven.','Room one.'],'A','CORRECTION','Room three đang cải tạo; dùng five.'),
mc('What does the fee include?',['A laptop.','Travel costs.','A meal.','Printed learning materials.'],'D','PARAPHRASE','“Handouts are covered by the price” = tài liệu in nằm trong phí.'),
mc('How much will the customer pay?',['Forty pounds.','Thirty-five pounds.','Thirty pounds.','Twenty pounds.'],'C','CORRECTION','Mức thường40; giảm early booking còn30.'),
mc('What will be practised in the first session?',['Writing a full research report.','Introducing oneself in a professional situation.','Repairing computers.','Preparing a budget.'],'B','PARAPHRASE','“Present yourself to a new colleague or client” tương đương giới thiệu bản thân trong công việc.')],script=[('Daniel','I would like to book the business communication course on Tuesday. Is there still a place?'),('Samantha','Tuesday is full, but we can offer Thursday.'),('Daniel','Thursday is possible. The website says six in the evening.'),('Samantha','That page has the previous timetable. The course now begins at six thirty and ends at eight.'),('Daniel','All right. Is it in Room three?'),('Samantha','Room three is being refurbished. We are using Room five during that work.'),('Daniel','Do I need to buy a workbook?'),('Samantha','No. Handouts are covered by the price. Please bring something to write with, but you will not need a laptop.'),('Daniel','The fee is forty pounds, correct?'),('Samantha','Usually, yes. You are booking before the end of this week, so the early booking rate is thirty pounds.'),('Daniel','What will we do in the first session?'),('Samantha','You will practise how to present yourself to a new colleague or client. Later sessions cover meetings and short emails.'),('Daniel','Then please book me for Thursday at six thirty, in Room five, at the thirty pound rate.'),('Samantha','Certainly. I will send the confirmation and payment details shortly.')],role='FINAL',rate=150)

add(7,87,'04_cuoi_chang_reading','Reading — Kiểm tra cuối chặng Advanced','READING','ADVANCED','Kiểm tra suy luận, quan điểm và mức độ hỗ trợ của bằng chứng.',
"""WHAT A COOLER STREET CAN TELL US
A city council planted trees along several residential streets as part of a summer heat project. Residents had complained that pavements and buildings retained heat long after sunset. The council wanted to improve shade and comfort, especially on routes used by people walking to shops and bus stops. It selected streets with few existing trees rather than distributing new planting evenly across the city.
After two summers, volunteers measured surface temperatures on shaded and unshaded sections of pavement. Shaded sections were generally cooler during afternoon measurements. Residents also reported that walking felt more comfortable. These findings support the idea that trees can improve conditions in the locations studied. They do not show that the same number of trees would produce an identical effect on every street. Building height, street direction and wind can influence local temperatures.
A newspaper headline described the project as proof that the city's heat problem had been solved. The project team rejected that interpretation. They had studied selected pavement sections, not the temperature inside every home or the whole city's exposure to heat. A person who cannot leave a hot apartment may gain little immediate relief from a shaded route elsewhere. The team therefore regarded the planting as one part of a broader response, alongside building improvements and access to cool public spaces.
Maintenance also matters. Young trees need water while their roots develop, and some planted trees did not survive their first summer. The council replaced them, but their loss delayed shade in those locations. A planting total alone would not reveal whether trees were alive, growing and providing useful cover. The team proposed reporting survival rates and canopy development together with the number planted.
Residents differed in their priorities. Some valued cooler walking routes; others worried about blocked light or damage to pavements. The council held meetings to identify specific concerns rather than assuming that opposition meant residents disliked trees. In some places, changing the species or planting position addressed the problem. In others, limited space required a different approach.
The next evaluation will compare streets with similar physical characteristics and record maintenance needs over several years. The team has not yet published the total long-term cost of the scheme. It hopes to learn where planting is most useful and what conditions allow it to succeed. This is a more limited ambition than a headline promising an instant citywide solution. It is also more informative for future decisions, because understanding the conditions of success helps avoid treating one encouraging result as a guarantee.""",[
mc('What is the author\'s main message?',['Tree planting is always ineffective.','One result proves every street will cool equally.','Planting totals are the only useful measure.','Local benefits should be interpreted with attention to limits and conditions.'],'D','MAIN_IDEA','Toàn bài ghi nhận lợi ích nhưng không suy rộng thành giải pháp toàn thành phố.'),
mc('Why did the project team reject the newspaper headline?',['The study covered selected surfaces rather than all heat exposure.','No measurements were made.','Every resident opposed planting.','The trees were artificial.'],'A','ARGUMENT','Đoạn ba: pavement sections không phải every home/whole city exposure.'),
mc('What can be inferred about counting planted trees alone?',['It proves all trees survive.','It measures apartment temperatures.','It can overstate usable shade if some trees die.','It makes maintenance unnecessary.'],'C','INFERENCE','Một số cây chết; total trồng không cho biết alive/growing/useful cover.'),
tf('The shaded pavement sections were generally cooler during afternoon measurements.','TRUE','Đoạn hai xác nhận trực tiếp generally cooler during afternoon measurements.'),
tf('The team claims the same number of trees will have an identical effect on every street.','FALSE','Đoạn hai nói findings “do not show” identical effect; các điều kiện đường khác nhau.'),
tf('The project\'s total long-term cost is higher than the cost of building improvements.','NOT GIVEN','Chưa công bố tổng long-term cost, không có so sánh giá với building improvements.')],role='FINAL')

add(7,88,'05_cuoi_chang_listening','Listening — Kiểm tra cuối chặng Advanced','LISTENING','ADVANCED','Kiểm tra lập luận, giới hạn bằng chứng và ý kiến từng người nói.','Discussing a trial of shorter meetings',[
mc('What was the trial mainly intended to test?',['Whether staff should stop communicating.','Whether shorter meetings could preserve useful discussion.','Whether all projects should be cancelled.','Whether offices should close.'],'B','MAIN_IDEA','Trial nhằm short meetings without losing information needed for decisions.'),
mc('Why does Helen avoid claiming that the trial increased productivity?',['No meeting took place.','Staff refused to answer.','Completed work was not measured directly.','Every meeting became longer.'],'C','ARGUMENT','Helen: measured meeting time, not quantity/quality completed work.'),
mc('What benefit does Marcus identify?',['More preparation before meetings.','Less access to information.','No need for decisions.','An end to all disagreements.'],'A','DETAIL','Marcus đọc agenda/documents trước, nên hỏi focused questions.'),
mc('Who worries that junior staff may not ask questions?',['Helen only.','Marcus only.','All speakers.','Nadia.'],'D','SPEAKER_MATCH','Nadia lo new colleagues hesitate to interrupt shorter meeting.'),
mc('What is Helen\'s attitude to continuing the trial?',['Certain that no changes are needed.','Supportive of further testing with better evidence.','Completely opposed.','Interested only in attendance totals.'],'B','AUTHOR_ATTITUDE','“Worth continuing ... better measures ... not ... universal rule”.'),
mc('Which adjustment does Nadia recommend?',['Remove the agenda.','Stop collecting feedback.','Allow a short question period after the main discussion.','Exclude new colleagues.'],'C','DETAIL','Nadia đề xuất short question period at end.')],script=[('Samantha',"""Helen: Our team tested twenty-minute meetings instead of the usual forty-minute sessions. The aim was to see whether shorter meetings could preserve the information needed for decisions. We saved meeting time, but I would not yet say productivity increased. We measured minutes in meetings, not the quantity or quality of completed work. Those are different outcomes."""),('Daniel',"""Marcus: For me, the shorter format encouraged better preparation. I read the agenda and supporting documents beforehand, because I knew there would not be time to discover the whole topic during the meeting. My questions became more focused. However, I already know most of the projects well. Someone unfamiliar with the background might need more explanation than I do."""),('Karen',"""Nadia: That is my concern. New colleagues sometimes hesitate to interrupt, especially when they can see the meeting is nearly over. A short session may look efficient while leaving their questions unanswered. I would keep a short question period after the main discussion. People could raise points that are essential for understanding without extending every agenda item."""),('Samantha',"""Helen: I think the trial is worth continuing with adjustments. We should collect feedback from junior as well as experienced staff, and compare decisions and follow-up work across similar projects. We should also record whether another meeting becomes necessary because something was unclear. The early results are useful, but they are not enough to make twenty minutes a universal rule.""")],role='FINAL',rate=160)

# Placement: 3 questions per skill per level; deliberately separate from practice and finals.
placement_reading_sections=[
('BEGINNER','A shop assistant',"""Nina is nineteen and lives in York. She works in a flower shop from nine in the morning to four in the afternoon. She walks to work because the shop is near her home. On Sundays, the shop is closed. Nina likes visiting her grandmother on that day. She is learning English at a local college on Tuesday evenings.""",[
mc('Where does Nina work?',['At a college.','In a flower shop.','In a hospital.','In a restaurant.'],'B','DETAIL','“Works in a flower shop”.','BEGINNER'),
mc('How does Nina travel to work?',['By bus.','By train.','She walks.','By taxi.'],'C','DETAIL','“She walks to work”.','BEGINNER'),
mc('When does Nina study English?',['Tuesday evenings.','Sunday mornings.','Friday afternoons.','Every morning.'],'A','DETAIL','“On Tuesday evenings”.','BEGINNER')]),
('INTERMEDIATE','A change to delivery',"""A small bookshop previously delivered every order on the day it was placed. This meant drivers sometimes made several trips to the same street. The owner introduced two delivery days each week to combine orders into fewer journeys. Customers could still collect books from the shop whenever it was open. After a month, fuel use fell, but some customers said waiting for delivery was inconvenient. The owner added a paid urgent-delivery option rather than returning to the old system. The shop has not yet measured whether the new arrangement changes total sales.""",[
mc('Why were fixed delivery days introduced?',['To close the shop.','To stop all collections.','To make drivers work every night.','To combine orders and reduce repeated journeys.'],'D','ARGUMENT','Nhiều trips cùng đường → combine orders vào fewer journeys.','INTERMEDIATE'),
mc('Which option remained available without waiting for delivery day?',['Free urgent delivery.','Collecting books at the shop.','Ordering only on Sundays.','Receiving every book online.'],'B','PARAPHRASE','“Collect ... whenever it was open”.','INTERMEDIATE'),
mc('Which outcome is reported?',['A reduction in fuel use.','A proven increase in sales.','An end to all complaints.','No delivery charge of any kind.'],'A','DETAIL','Fuel use fell; sales chưa đo, urgent option có phí.','INTERMEDIATE')]),
('ADVANCED','Interpreting a survey',"""A university asked students whether recorded lectures helped them study. Most respondents described the recordings as useful, especially when reviewing an unfamiliar explanation. A report then claimed that recordings had improved examination performance. That conclusion goes beyond the survey: students reported perceived usefulness, while examination outcomes were not measured. Moreover, participation was voluntary, so respondents may not represent all students. These limitations do not show that recordings are ineffective. They show that evidence for one claim cannot automatically establish another. A stronger evaluation would examine how recordings are used, compare relevant learning outcomes and consider differences in prior knowledge. Student opinions remain valuable for understanding experience, but should not be presented as a direct measurement of achievement.""",[
mc('What is the author\'s main criticism?',['The survey asked no students.','Recordings cannot ever help.','Perceived usefulness was treated as proof of improved performance.','Every volunteer was dishonest.'],'C','ARGUMENT','Reported usefulness khác measured exam outcomes.','ADVANCED'),
mc('What can be inferred about voluntary participation?',['Every student participated.','Respondents must have failed.','The survey has no value at all.','The views collected may not represent the whole student population.'],'D','INFERENCE','“May not represent all students”.','ADVANCED'),
mc('What is the author\'s attitude towards student opinions?',['Useful within their limits.','Always superior to assessment.','Completely irrelevant.','A guarantee of exam success.'],'A','AUTHOR_ATTITUDE','“Remain valuable ... experience” nhưng không direct achievement measure.','ADVANCED')])]
add(12,None,'01_danh_gia_dau_vao_reading','Đánh giá đầu vào — Reading','READING','MIXED','Gợi ý mức bắt đầu Reading qua 3 nhóm câu hỏi tăng độ khó.','',[],role='PLACEMENT')
EXAMS[-1]['sections']=placement_reading_sections
EXAMS[-1]['questions']=[q for _,_,_,questions in placement_reading_sections for q in questions]
placement_listening_sections=[
('BEGINNER','A library visit',[
('Samantha',"""My name is Emma. I go to the town library every Friday after school. The library closes at five, so I usually arrive at four. I borrow two books each week. I enjoy stories about animals. My father collects me at half past four, and we go home together. On Saturday, I read one of my new books in the garden.""",115)], [
mc('On which day does Emma visit the library?',['Thursday.','Friday.','Saturday.','Sunday.'],'B','DETAIL','“Every Friday after school”.','BEGINNER'),
mc('What time does she usually arrive?',['Four.','Five.','Four thirty.','Three.'],'A','DETAIL','“Usually arrive at four”.','BEGINNER'),
mc('Who collects her?',['Her teacher.','Her sister.','Her mother.','Her father.'],'D','DETAIL','“My father collects me”.','BEGINNER')]),
('INTERMEDIATE','A changed booking',[
('Daniel',"""This is a message about your appointment at the careers centre. We originally booked you for Monday at two, but your adviser will be attending training that afternoon. Your appointment has moved to Wednesday at three. It will still last thirty minutes. Please come to Room six instead of Room four, which is being painted. You do not need to print your application. Bring it on your laptop or email it to us beforehand. If the new time is not suitable, contact reception to arrange another day.""",145)], [
mc('What is the new appointment time?',['Monday at two.','Wednesday at two.','Wednesday at three.','Monday at three.'],'C','CORRECTION','“Moved to Wednesday at three”.','INTERMEDIATE'),
mc('Which room should the listener use?',['Room six.','Room four.','Room three.','Room two.'],'A','CORRECTION','“Room six instead of Room four”.','INTERMEDIATE'),
mc('What is required about the application?',['It must be printed.','It must be delivered by post.','It must be handwritten.','It can be provided electronically.'],'D','PARAPHRASE','Laptop hoặc email là cung cấp điện tử; không cần print.','INTERMEDIATE')]),
('ADVANCED','Evaluating a mentoring pilot',[
('Karen',"""Our mentoring pilot received positive feedback, but that should not be confused with proof that it caused better career outcomes. Participants chose to join, and some may already have had strong motivation. We also collected feedback immediately after the final session, when enthusiasm could be high. I would keep the programme because participants found the conversations useful, while evaluating it more carefully. A later follow-up could show whether advice was applied. Comparing similar participants with different levels of access might also help, although such comparisons would still need cautious interpretation. The reasonable conclusion is that the pilot deserves further investigation, not that every participant is guaranteed a promotion.""",160)], [
mc('Why does the speaker question a causal claim?',['Nobody attended.','Participants selected themselves and may differ in motivation.','Feedback was always negative.','Promotion was measured for everyone.'],'B','ARGUMENT','Self-selection và motivation có thể tạo khác biệt.','ADVANCED'),
mc('What is the speaker\'s attitude towards the programme?',['Certain it guarantees promotion.','Determined to close it.','Supportive but cautious about evidence.','Interested only in attendance.'],'C','AUTHOR_ATTITUDE','Keep programme nhưng evaluate carefully.','ADVANCED'),
mc('Why is a later follow-up suggested?',['To see whether advice was put into practice.','To remove every mentor.','To avoid collecting information.','To guarantee immediate enthusiasm.'],'A','INFERENCE','“Show whether advice was applied”.','ADVANCED')])]
add(12,None,'02_danh_gia_dau_vao_listening','Đánh giá đầu vào — Listening','LISTENING','MIXED','Gợi ý mức bắt đầu Listening qua 3 nhóm câu hỏi tăng độ khó.','',[],role='PLACEMENT',rate=140)
EXAMS[-1]['sections']=[(level,title,'Listen to this section.',questions) for level,title,script,questions in placement_listening_sections]
EXAMS[-1]['questions']=[q for _,_,_,questions in placement_listening_sections for q in questions]
EXAMS[-1]['script']=[]
for n,(level,title,script,questions) in enumerate(placement_listening_sections,1):
    EXAMS[-1]['script'].append(('Daniel',f'Section {n}. Questions {(n-1)*3+1} to {n*3}.',130))
    EXAMS[-1]['script'].extend(script)

WRITING=[
dict(course=11,lesson=74,slug='03_writing_quan_diem',title='Writing Task 2: Trình bày quan điểm',level='INTERMEDIATE',focus='TASK_2',
chart=dict(title='Preferred study location in a fictional college',labels=['Home','Library','Campus cafe'],years=[2018,2024],values=[[50,35,15],[40,45,15]]),
task1="The chart shows the percentages of students who preferred three study locations at a fictional college in 2018 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
task2="Some people prefer studying alone, while others prefer studying in groups. Discuss both views and give your own opinion. Write at least 250 words.",
notes1='Overview: home giảm, library tăng và trở thành lựa chọn phổ biến nhất; cafe không đổi. Home 50→40%; library 35→45%; cafe 15→15%. Không giải thích nguyên nhân vì biểu đồ không cung cấp.',
notes2='Mở bài giới thiệu hai cách học và nêu quan điểm. Đoạn 1: học một mình giúp tự điều chỉnh tốc độ và tập trung; đưa ví dụ. Đoạn 2: học nhóm giúp giải thích, phản hồi; nêu hạn chế nếu thiếu mục tiêu. Kết luận có thể chọn phối hợp theo nhiệm vụ nhưng phải nhất quán với quan điểm mở bài.'),
dict(course=7,lesson=77,slug='03_writing_so_sanh_du_lieu',title='Writing Task 1: So sánh dữ liệu',level='ADVANCED',focus='TASK_1',
chart=dict(title='Travel to work in a fictional town',labels=['Car','Public transport','Bicycle'],years=[2010,2020],values=[[60,30,10],[45,35,20]]),
task1="The chart shows how workers travelled to work in a fictional town in 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
task2="Some cities encourage people to use public transport instead of private cars. To what extent do you agree or disagree with this approach? Write at least 250 words.",
notes1='Overview: car vẫn cao nhất nhưng giảm; public transport và bicycle tăng. Car giảm15 điểm phần trăm; public transport tăng5; bicycle tăng10 và tỷ lệ gấp đôi. Không nhầm tăng10 điểm phần trăm với tăng10%. Chia body theo xu hướng giảm/tăng hoặc so sánh hai năm.',
notes2='Chọn mức đồng ý rõ. Giải thích lợi ích giảm tắc nghẽn và tăng tiếp cận; thừa nhận cần dịch vụ đáng tin cậy và ngoại lệ cho vùng thiếu tuyến. Không chỉ liệt kê lợi ích mà phải giải thích quan hệ với chính sách.'),
dict(course=8,lesson=80,slug='03_writing_loi_ich_bat_loi',title='Writing Task 2: Đánh giá lợi ích và bất lợi',level='ADVANCED',focus='TASK_2',
chart=dict(title='Working arrangements in a fictional company',labels=['Office only','Hybrid','Remote only'],years=[2019,2024],values=[[80,15,5],[35,45,20]]),
task1="The chart shows the percentages of employees using three working arrangements in a fictional company in 2019 and 2024. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
task2="More companies allow employees to work from home. Do the advantages outweigh the disadvantages? Write at least 250 words.",
notes1='Overview: office only giảm mạnh; hybrid trở thành nhóm lớn nhất; remote only cũng tăng. Office80→35; hybrid15→45; remote5→20. Mỗi năm cộng100%. Mô tả phân bố, không tự đưa lý do như đại dịch vào báo cáo.',
notes2='Nêu rõ advantages có outweigh disadvantages hay không. So sánh mức độ/tầm quan trọng, không chỉ đếm số ý. Có thể lập luận giảm đi lại và linh hoạt có giá trị khi có phối hợp rõ; phản biện khó đào tạo người mới và ranh giới công việc. Ví dụ phải hỗ trợ luận điểm và kết luận nhất quán.')]

# Contextual vocabulary questions require inference from nearby definitions/examples.
for exam in EXAMS:
    if exam['lesson'] == 68:
        for question in exam['questions']:
            question['tag'] = 'INFERENCE'
