#!/bin/bash
awk '
/<!-- Course List Section -->/ {
    print "    <!-- Hot/Sale Courses Slider -->"
    print "    <div class=\"container mt-5 mb-5\" th:with=\"saleCourses=${courses.?[salePrice != null]}\">"
    print "        <th:block th:if=\"${not #lists.isEmpty(saleCourses)}\">"
    print "            <div class=\"d-flex justify-content-between align-items-center mb-4\">"
    print "                <h3 class=\"fw-bold text-danger mb-0\">"
    print "                    <i class=\"bi bi-fire me-2\"></i>Ưu Đãi Đặc Biệt & Khóa Học Hot"
    print "                </h3>"
    print "                <div class=\"d-flex gap-2\">"
    print "                    <button class=\"btn btn-outline-danger rounded-circle shadow-sm\" type=\"button\" data-bs-target=\"#hotCoursesCarousel\" data-bs-slide=\"prev\" style=\"width: 40px; height: 40px;\">"
    print "                        <i class=\"bi bi-chevron-left\"></i>"
    print "                    </button>"
    print "                    <button class=\"btn btn-outline-danger rounded-circle shadow-sm\" type=\"button\" data-bs-target=\"#hotCoursesCarousel\" data-bs-slide=\"next\" style=\"width: 40px; height: 40px;\">"
    print "                        <i class=\"bi bi-chevron-right\"></i>"
    print "                    </button>"
    print "                </div>"
    print "            </div>"
    print "            "
    print "            <div id=\"hotCoursesCarousel\" class=\"carousel slide\" data-bs-ride=\"carousel\" data-bs-interval=\"4000\">"
    print "                <div class=\"carousel-inner rounded-4 shadow-sm\" style=\"border: 2px solid #dc3545;\">"
    print "                    <th:block th:each=\"course : ${saleCourses}\">"
    print "                        <div class=\"carousel-item hot-carousel-item\">"
    print "                            <div class=\"card border-0 bg-white overflow-hidden\" style=\"background: linear-gradient(135deg, #ffffff 50%, #fff5f5 100%);\">"
    print "                                <div class=\"row g-0 align-items-center\">"
    print "                                    <div class=\"col-md-5 position-relative bg-light\" style=\"min-height: 300px;\">"
    print "                                        <div th:if=\"${course.thumbnailUrl != null}\" class=\"w-100 h-100 d-flex justify-content-center align-items-center\" style=\"position: absolute; top: 0; left: 0;\">"
    print "                                            <img th:src=\"${course.thumbnailUrl}\" class=\"w-100 h-100\" style=\"object-fit: cover;\" alt=\"Banner\">"
    print "                                        </div>"
    print "                                        <div class=\"position-absolute top-0 start-0 m-3\">"
    print "                                            <span class=\"badge bg-danger fs-6 px-3 py-2 shadow rounded-pill\">"
    print "                                                <i class=\"bi bi-lightning-charge-fill me-1\"></i>Ưu Đãi Lớn"
    print "                                            </span>"
    print "                                        </div>"
    print "                                    </div>"
    print "                                    <div class=\"col-md-7 p-4 p-md-5\">"
    print "                                        <div class=\"d-flex align-items-center mb-2\">"
    print "                                            <span class=\"badge bg-primary bg-opacity-10 text-primary me-2 px-2 py-1\" th:text=\"${course.level}\"></span>"
    print "                                            <span class=\"text-danger fw-bold small\"><i class=\"bi bi-clock-history me-1\"></i>Thời gian có hạn</span>"
    print "                                        </div>"
    print "                                        <h2 class=\"fw-bold text-dark mb-3\" th:text=\"${course.title}\"></h2>"
    print "                                        <p class=\"text-muted mb-4 fs-6\" th:text=\"${course.description}\" style=\"display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden;\"></p>"
    print "                                        <div class=\"d-flex align-items-center mb-4\">"
    print "                                            <span class=\"text-muted text-decoration-line-through fs-5 me-3\" th:text=\"${course.price != null ? #numbers.formatDecimal(course.price, 0, \"COMMA\", 0, \"POINT\") + \" đ\" : \"\"}\"></span>"
    print "                                            <span class=\"text-danger fw-bold display-6\" th:text=\"${course.salePrice != null ? #numbers.formatDecimal(course.salePrice, 0, \"COMMA\", 0, \"POINT\") + \" đ\" : \"\"}\"></span>"
    print "                                        </div>"
    print "                                        <a th:href=\"@{'/courses/' + ${course.id}}\" class=\"btn btn-danger btn-lg rounded-pill px-5 fw-bold shadow\">"
    print "                                            <i class=\"bi bi-cart-check-fill me-2\"></i>Đăng ký ngay"
    print "                                        </a>"
    print "                                    </div>"
    print "                                </div>"
    print "                            </div>"
    print "                        </div>"
    print "                    </th:block>"
    print "                </div>"
    print "            </div>"
    print "        </th:block>"
    print "    </div>"
    print ""
}
{ print }
' src/main/resources/templates/index.html > scratch/new_index.html && mv scratch/new_index.html src/main/resources/templates/index.html
